version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "5432:5432"

  auth-service:
    build: ./auth-service
    container_name: auth_service
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3001:3001"

  users-service:
    build: ./users-service
    container_name: users_service
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3002:3002"

  companies-service:
    build: ./companies-service
    container_name: companies_service
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - "3003:3003"

  gateway:
    build: ./gateway
    container_name: api_gateway
    depends_on:
      - auth-service
      - users-service
      - companies-service
    ports:
      - "8080:8080"

volumes:
  pgdata:
